header:
  schema-version: 2.0.0
  last-updated: '2026-04-12'
  last-reviewed: '2026-04-12'
  url: https://github.com/fluxcd/.github/blob/main/.github/security-insights.yml
  comment: |
    This file contains the security insights information for the Flux project.

project:
  name: Flux
  homepage: https://fluxcd.io
  roadmap: https://fluxcd.io/roadmap/
  administrators:
    - name: Stefan Prodan
      affiliation: ControlPlane
      social: @stefanprodan
      primary: true
    - name: Hidde Beydals
      affiliation: Independent
      social: @hiddeco
    - name: Michael Bridgen
      affiliation: Independent
      social: @squaremo
  documentation:
    quickstart-guide: https://fluxcd.io/flux/get-started/
    release-process: https://fluxcd.io/flux/releases/
    signature-verification: https://fluxcd.io/flux/security/
    code-of-conduct: https://github.com/fluxcd/.github/blob/main/CODE_OF_CONDUCT.md
  repositories:
    - name: fluxcd/flux2
      url: https://github.com/fluxcd/flux2
      comment: |
        The Flux distribution and command-line interface (CLI)
    - name: fluxcd/pkg
      url: https://github.com/fluxcd/pkg
      comment: |
        The GitOps Toolkit Go SDK for building Flux controllers and CLI plugins
    - name: fluxcd/source-controller
      url: https://github.com/fluxcd/source-controller
      comment: |
        Kubernetes operator for managing sources (Git, OCI and Helm repositories, S3-compatible Buckets)
    - name: fluxcd/source-watcher
      url: https://github.com/fluxcd/source-watcher
      comment: |
        Kubernetes operator for advanced source composition and decomposition patterns
    - name: fluxcd/kustomize-controller
      url: https://github.com/fluxcd/kustomize-controller
      comment: |
        Kubernetes operator for building GitOps pipelines with Kustomize
    - name: fluxcd/helm-controller
      url: https://github.com/fluxcd/helm-controller
      comment: |
        Kubernetes operator for lifecycle management of Helm releases
    - name: fluxcd/notification-controller
      url: https://github.com/fluxcd/notification-controller
      comment: |
        Kubernetes operator for handling inbound and outbound events (alerts and webhook receivers)
    - name: fluxcd/image-reflector-controller
      url: https://github.com/fluxcd/image-reflector-controller
      comment: |
        Kubernetes operator for scanning container registries for new image tags and digests
    - name: fluxcd/image-automation-controller
      url: https://github.com/fluxcd/image-automation-controller
      comment: |
        Kubernetes operator for patching container image tags and digests in Git repositories
    - name: fluxcd/flagger
      url: https://github.com/fluxcd/flagger
      comment: |
        Progressive delivery Kubernetes operator (Canary, A/B Testing and Blue/Green deployments)
    - name: fluxcd/website
      url: https://github.com/fluxcd/website
      comment: |
        The Flux documentation website
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false
    contact:
      name: The Flux security team.
      email: cncf-flux-security@lists.cncf.io
      primary: true
    security-policy: https://github.com/fluxcd/.github/blob/main/SECURITY.md
